In [1]:
import pandas as pd
import re
import warnings 

warnings.filterwarnings('ignore')
#petit clean 
df = pd.read_csv("./data/labeled_data.csv", usecols=['class', 'tweet'])
df['tweet'] = df['tweet'].apply(lambda tweet: re.sub('[^A-Za-z]+', ' ', tweet.lower()))


In [2]:
df = df.sample(frac=.25)
print(df.size)

12392


In [3]:
#labels 
# 0 - hate speech 1 - offensive language 2 - neither
from sklearn.pipeline import make_pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.multiclass import OneVsRestClassifier
from sklearn.svm import SVC
from stop_words import get_stop_words

In [4]:
#pipeline 
clf = make_pipeline(
    TfidfVectorizer(stop_words=get_stop_words('en')),
    OneVsRestClassifier(SVC(kernel='linear', probability=True))
)

In [5]:
#fit 
clf = clf.fit(X=df['tweet'], y=df['class'])

In [6]:
clf

Pipeline(memory=None,
         steps=[('tfidfvectorizer',
                 TfidfVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.float64'>,
                                 encoding='utf-8', input='content',
                                 lowercase=True, max_df=1.0, max_features=None,
                                 min_df=1, ngram_range=(1, 1), norm='l2',
                                 preprocessor=None, smooth_idf=True,
                                 stop_words=['a', 'about', 'above', 'after',
                                             'again', 'against', '...
                                 tokenizer=None, use_idf=True,
                                 vocabulary=None)),
                ('onevsrestclassifier',
                 OneVsRestClassifier(estimator=SVC(C=1.0, break_ties=False,
                                                   cache_size=200,
                      

In [7]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

kfold = KFold(n_splits=10, random_state=None)
results = cross_val_score(clf, df['tweet'], df['class'], cv=kfold)
print(results.mean())

0.8904142998592945


In [10]:
predicted = clf.predict_proba(df['tweet'])
print(predicted)

[[0.04100369 0.95771735 0.00127896]
 [0.04134235 0.94114345 0.0175142 ]
 [0.05013248 0.9456249  0.00424262]
 ...
 [0.02045686 0.96358447 0.01595867]
 [0.04272951 0.95555246 0.00171803]
 [0.00683306 0.05547942 0.93768753]]
